version: '3.8'

services:
  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50M'
    network_mode: bridge

  api01: &api_service
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '150M'
    network_mode: bridge

  api02:
    <<: *api_service
    
# A soma dos recursos define o teto da rinha:
# CPU: 0.2 (lb) + 0.4 (api1) + 0.4 (api2) = 1.0 CPU
# Memória: 50M (lb) + 150M (api1) + 150M (api2) = 350M
